
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class AchiData : Luban.BeanBase
{
    public AchiData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Title"].IsString) { throw new SerializationException(); }  Title = _buf["Title"]; }
        { if(!_buf["Content"].IsString) { throw new SerializationException(); }  Content = _buf["Content"]; }
        { if(!_buf["Icon"].IsString) { throw new SerializationException(); }  Icon = _buf["Icon"]; }
    }

    public static AchiData DeserializeAchiData(JSONNode _buf)
    {
        return new AchiData(_buf);
    }

    public readonly int ID;
    public readonly string Title;
    public readonly string Content;
    public readonly string Icon;
   
    public const int __ID__ = -1936369907;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Title:" + Title + ","
        + "Content:" + Content + ","
        + "Icon:" + Icon + ","
        + "}";
    }
}

}
