
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class AttrData : Luban.BeanBase
{
    public AttrData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["BaseAttr"].IsObject) { throw new SerializationException(); }  BaseAttr = SLG.BasicStats.DeserializeBasicStats(_buf["BaseAttr"]);  }
    }

    public static AttrData DeserializeAttrData(JSONNode _buf)
    {
        return new AttrData(_buf);
    }

    public readonly int ID;
    public readonly SLG.BasicStats BaseAttr;
   
    public const int __ID__ = 618152283;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        BaseAttr?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BaseAttr:" + BaseAttr + ","
        + "}";
    }
}

}
