
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CharacterData : Luban.BeanBase
{
    public CharacterData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["CharName"].IsString) { throw new SerializationException(); }  CharName = _buf["CharName"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
        { if(!_buf["Gender"].IsNumber) { throw new SerializationException(); }  Gender = (SLG.Gender)_buf["Gender"].AsInt; }
    }

    public static CharacterData DeserializeCharacterData(JSONNode _buf)
    {
        return new CharacterData(_buf);
    }

    public readonly int ID;
    public readonly string CharName;
    public readonly string Description;
    public readonly SLG.Gender Gender;
   
    public const int __ID__ = -991456685;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "CharName:" + CharName + ","
        + "Description:" + Description + ","
        + "Gender:" + Gender + ","
        + "}";
    }
}

}
