
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ClassData : Luban.BeanBase
{
    public ClassData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["Description"].IsString) { throw new SerializationException(); }  Description = _buf["Description"]; }
    }

    public static ClassData DeserializeClassData(JSONNode _buf)
    {
        return new ClassData(_buf);
    }

    public readonly int ID;
    public readonly string Name;
    public readonly string Description;
   
    public const int __ID__ = 1993781538;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Description:" + Description + ","
        + "}";
    }
}

}
