
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ConstData : Luban.BeanBase
{
    public ConstData(JSONNode _buf) 
    {
        { if(!_buf["TestConstValue"].IsNumber) { throw new SerializationException(); }  TestConstValue = _buf["TestConstValue"]; }
    }

    public static ConstData DeserializeConstData(JSONNode _buf)
    {
        return new ConstData(_buf);
    }

    /// <summary>
    /// test read this value 
    /// </summary>
    public readonly long TestConstValue;
   
    public const int __ID__ = 1580814733;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
    }

    public override string ToString()
    {
        return "{ "
        + "TestConstValue:" + TestConstValue + ","
        + "}";
    }
}

}
