
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DialogueData : Luban.BeanBase
{
    public DialogueData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Content"].IsString) { throw new SerializationException(); }  Content = _buf["Content"]; }
        { if(!_buf["Option1"].IsString) { throw new SerializationException(); }  Option1 = _buf["Option1"]; }
        { if(!_buf["OPAction1"].IsNumber) { throw new SerializationException(); }  OPAction1 = _buf["OPAction1"]; }
        { if(!_buf["Option2"].IsString) { throw new SerializationException(); }  Option2 = _buf["Option2"]; }
        { if(!_buf["OPAction2"].IsNumber) { throw new SerializationException(); }  OPAction2 = _buf["OPAction2"]; }
        { if(!_buf["Option3"].IsString) { throw new SerializationException(); }  Option3 = _buf["Option3"]; }
        { if(!_buf["OPAction3"].IsNumber) { throw new SerializationException(); }  OPAction3 = _buf["OPAction3"]; }
        { if(!_buf["Option4"].IsString) { throw new SerializationException(); }  Option4 = _buf["Option4"]; }
        { if(!_buf["OPAction4"].IsNumber) { throw new SerializationException(); }  OPAction4 = _buf["OPAction4"]; }
    }

    public static DialogueData DeserializeDialogueData(JSONNode _buf)
    {
        return new DialogueData(_buf);
    }

    public readonly int ID;
    public readonly string Content;
    public readonly string Option1;
    public readonly int OPAction1;
    public readonly string Option2;
    public readonly int OPAction2;
    public readonly string Option3;
    public readonly int OPAction3;
    public readonly string Option4;
    public readonly int OPAction4;
   
    public const int __ID__ = 1514857922;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Content:" + Content + ","
        + "Option1:" + Option1 + ","
        + "OPAction1:" + OPAction1 + ","
        + "Option2:" + Option2 + ","
        + "OPAction2:" + OPAction2 + ","
        + "Option3:" + Option3 + ","
        + "OPAction3:" + OPAction3 + ","
        + "Option4:" + Option4 + ","
        + "OPAction4:" + OPAction4 + ","
        + "}";
    }
}

}
