
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class QuestData : Luban.BeanBase
{
    public QuestData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["platform"].IsBoolean) { throw new SerializationException(); }  Platform = _buf["platform"]; }
        { if(!_buf["Title"].IsString) { throw new SerializationException(); }  Title = _buf["Title"]; }
        { if(!_buf["Content"].IsString) { throw new SerializationException(); }  Content = _buf["Content"]; }
        { if(!_buf["QuestType"].IsNumber) { throw new SerializationException(); }  QuestType = _buf["QuestType"]; }
        { if(!_buf["RewardGold"].IsNumber) { throw new SerializationException(); }  RewardGold = _buf["RewardGold"]; }
        { if(!_buf["Param1"].IsNumber) { throw new SerializationException(); }  Param1 = _buf["Param1"]; }
        { if(!_buf["GoldCount"].IsNumber) { throw new SerializationException(); }  GoldCount = _buf["GoldCount"]; }
    }

    public static QuestData DeserializeQuestData(JSONNode _buf)
    {
        return new QuestData(_buf);
    }

    public readonly int ID;
    public readonly bool Platform;
    public readonly string Title;
    public readonly string Content;
    public readonly int QuestType;
    public readonly int RewardGold;
    public readonly int Param1;
    public readonly int GoldCount;
   
    public const int __ID__ = 220617612;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "platform:" + Platform + ","
        + "Title:" + Title + ","
        + "Content:" + Content + ","
        + "QuestType:" + QuestType + ","
        + "RewardGold:" + RewardGold + ","
        + "Param1:" + Param1 + ","
        + "GoldCount:" + GoldCount + ","
        + "}";
    }
}

}
