
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.SLG
{ 
    public enum DamageType
    {
        NONE = 0,
        /// <summary>
        /// physics
        /// </summary>
        PH = 1,
        /// <summary>
        /// magic
        /// </summary>
        MAG = 2,
        /// <summary>
        /// penetrating
        /// </summary>
        PN = 3,
    }

} 

