
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public partial class TbQuest
{
    private readonly System.Collections.Generic.Dictionary<int, QuestData> _dataMap;
    private readonly System.Collections.Generic.List<QuestData> _dataList;
    
    public TbQuest(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, QuestData>();
        _dataList = new System.Collections.Generic.List<QuestData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            QuestData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = QuestData.DeserializeQuestData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, QuestData> DataMap => _dataMap;
    public System.Collections.Generic.List<QuestData> DataList => _dataList;

    public QuestData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public QuestData Get(int key) => _dataMap[key];
    public QuestData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

