
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.SLG
{ 
    public enum Gender
    {
        NONE = 0,
        MALE = 1,
        FEMALE = 2,
    }

} 

