
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.SLG
{ 
    public enum ClassType
    {
        None = 0,
        Armor = 1,
        Backup = 2,
        Cavalry = 3,
        Covert = 4,
        Dragon = 5,
        Flying = 6,
        Mystical = 7,
        QiAdept = 8,
    }

} 

