
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.SLG
{ 
    public enum WeaponType
    {
        /// <summary>
        /// 剑
        /// </summary>
        Sword = 0,
        /// <summary>
        /// 枪
        /// </summary>
        Lance = 1,
        /// <summary>
        /// 斧
        /// </summary>
        Axe = 2,
        /// <summary>
        /// 弓
        /// </summary>
        Bow = 3,
        /// <summary>
        /// 短刀
        /// </summary>
        Dagger = 4,
        /// <summary>
        /// 魔法书
        /// </summary>
        Tome = 5,
        /// <summary>
        /// 杖
        /// </summary>
        Special = 6,
        /// <summary>
        /// 体术
        /// </summary>
        Arts = 7,
        /// <summary>
        /// 特殊
        /// </summary>
        Staff = 8,
    }

} 

