
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public partial class Item
{
    private readonly System.Collections.Generic.Dictionary<int, ItemData> _dataMap;
    private readonly System.Collections.Generic.List<ItemData> _dataList;
    
    public Item(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ItemData>();
        _dataList = new System.Collections.Generic.List<ItemData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ItemData.DeserializeItemData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ItemData> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemData> DataList => _dataList;

    public ItemData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemData Get(int key) => _dataMap[key];
    public ItemData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

