
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.SLG
{ 
    public enum WeaponRank
    {
        S = 0,
        A = 1,
        B = 2,
        C = 3,
        D = 4,
        E = 5,
    }

} 

