
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.SLG
{ 
    public enum PawnMapEvent
    {
        Default = 0,
        Combat = 1,
        Store = 2,
        Talk = 3,
    }

} 

