
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public partial class TbAchi
{
    private readonly System.Collections.Generic.Dictionary<int, AchiData> _dataMap;
    private readonly System.Collections.Generic.List<AchiData> _dataList;
    
    public TbAchi(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AchiData>();
        _dataList = new System.Collections.Generic.List<AchiData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            AchiData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = AchiData.DeserializeAchiData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AchiData> DataMap => _dataMap;
    public System.Collections.Generic.List<AchiData> DataList => _dataList;

    public AchiData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AchiData Get(int key) => _dataMap[key];
    public AchiData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

