
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public partial class TbAttr
{
    private readonly System.Collections.Generic.Dictionary<int, AttrData> _dataMap;
    private readonly System.Collections.Generic.List<AttrData> _dataList;
    
    public TbAttr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, AttrData>();
        _dataList = new System.Collections.Generic.List<AttrData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            AttrData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = AttrData.DeserializeAttrData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AttrData> DataMap => _dataMap;
    public System.Collections.Generic.List<AttrData> DataList => _dataList;

    public AttrData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AttrData Get(int key) => _dataMap[key];
    public AttrData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

