
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public sealed partial class BasicStats : Luban.BeanBase
{
    public BasicStats(JSONNode _buf) 
    {
        { if(!_buf["HPMax"].IsNumber) { throw new SerializationException(); }  HPMax = _buf["HPMax"]; }
        { if(!_buf["SPMax"].IsNumber) { throw new SerializationException(); }  SPMax = _buf["SPMax"]; }
        { if(!_buf["Patk"].IsNumber) { throw new SerializationException(); }  Patk = _buf["Patk"]; }
        { if(!_buf["Pdef"].IsNumber) { throw new SerializationException(); }  Pdef = _buf["Pdef"]; }
        { if(!_buf["Eatk"].IsNumber) { throw new SerializationException(); }  Eatk = _buf["Eatk"]; }
        { if(!_buf["Edef"].IsNumber) { throw new SerializationException(); }  Edef = _buf["Edef"]; }
        { if(!_buf["Accuracy"].IsNumber) { throw new SerializationException(); }  Accuracy = _buf["Accuracy"]; }
        { if(!_buf["Speed"].IsNumber) { throw new SerializationException(); }  Speed = _buf["Speed"]; }
        { if(!_buf["Critical"].IsNumber) { throw new SerializationException(); }  Critical = _buf["Critical"]; }
        { if(!_buf["Evasion"].IsNumber) { throw new SerializationException(); }  Evasion = _buf["Evasion"]; }
    }

    public static BasicStats DeserializeBasicStats(JSONNode _buf)
    {
        return new SLG.BasicStats(_buf);
    }

    public readonly int HPMax;
    public readonly int SPMax;
    /// <summary>
    /// 物理攻击力
    /// </summary>
    public readonly int Patk;
    /// <summary>
    /// 物理防御力
    /// </summary>
    public readonly int Pdef;
    /// <summary>
    /// 元素攻击力
    /// </summary>
    public readonly int Eatk;
    /// <summary>
    /// 元素防御力
    /// </summary>
    public readonly int Edef;
    /// <summary>
    /// 准确率
    /// </summary>
    public readonly int Accuracy;
    /// <summary>
    /// 速度
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 暴击率
    /// </summary>
    public readonly int Critical;
    /// <summary>
    /// 回避率
    /// </summary>
    public readonly int Evasion;
   
    public const int __ID__ = 542478865;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "HPMax:" + HPMax + ","
        + "SPMax:" + SPMax + ","
        + "Patk:" + Patk + ","
        + "Pdef:" + Pdef + ","
        + "Eatk:" + Eatk + ","
        + "Edef:" + Edef + ","
        + "Accuracy:" + Accuracy + ","
        + "Speed:" + Speed + ","
        + "Critical:" + Critical + ","
        + "Evasion:" + Evasion + ","
        + "}";
    }
}

}
