
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.SLG
{
public partial class TbDialogue
{
    private readonly System.Collections.Generic.Dictionary<int, DialogueData> _dataMap;
    private readonly System.Collections.Generic.List<DialogueData> _dataList;
    
    public TbDialogue(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DialogueData>();
        _dataList = new System.Collections.Generic.List<DialogueData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DialogueData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = DialogueData.DeserializeDialogueData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DialogueData> DataMap => _dataMap;
    public System.Collections.Generic.List<DialogueData> DataList => _dataList;

    public DialogueData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DialogueData Get(int key) => _dataMap[key];
    public DialogueData this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

