
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.SLG
{ 
    public enum ItemType
    {
        Sword = 0,
        Lance = 1,
        Axe = 2,
        Bow = 3,
        Dagger = 4,
        Tome = 5,
        Special = 6,
        Arts = 7,
        Staff = 8,
        Item = 9,
    }

} 

